name: chowmin_shop
description: "A professional ChowMin Shop App with Customer and Admin functionality"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  lottie: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  confetti: ^0.7.0

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_messaging: ^14.7.9

  # State Management
  provider: ^6.1.1
  get: ^4.6.6

  # Local Storage
  shared_preferences: ^2.2.2

  # Payment
  razorpay_flutter: ^1.3.6
  # upi_india: ^3.0.1  # Temporarily disabled due to compatibility issues
  # TODO: Re-enable when plugin is updated for Flutter 3.x

  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3
  image_picker: ^1.0.7
  permission_handler: ^11.2.0
  url_launcher: ^6.2.4
  fluttertoast: ^8.2.4
  connectivity_plus: ^5.0.2
  
  # Animations & Effects
  animate_do: ^3.1.2
  flutter_animate: ^4.5.0
  rive: ^0.12.4
  
  # Notifications & Updates
  flutter_local_notifications: ^17.0.0
  badges: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#C62828"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  
  # Fonts: Using default system fonts for now
  # To add custom Poppins fonts later:
  # 1. Download from https://fonts.google.com/specimen/Poppins
  # 2. Place .ttf files in assets/fonts/
  # 3. Uncomment the fonts section below
  
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: assets/fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Poppins-Bold.ttf
  #         weight: 700
